### ISSUE TITLE
Semantic Search for images with text in the frontend is not working properly

### ISSUE THREAD

**Issue by floschne** [uhh-lt/dats#137]
When searching images with text queries via semantic search,

 no results are displayed. 

![Image](https://user-images.githubusercontent.com/11663441/261281530-d5a27e39-5633-4d93-a6f7-f6070ef7d1ac.png)

**Steps to reproduce**

1. https://dwts.ltdemos.informatik.uni-hamburg.de/project/1/search/
2. Click into search bar
3. De-select "Text" modality
4. Select "Semantic" search type
5. Search for "Forest fires are dangerous"

**Comment by bigabig** [comment]
this was completely reworked in #389 . We now have seperate doc, image, sentence search views. In image seach view, you can search for images with text.
