### ISSUE TITLE
Rebranding: From DWTS to DATS

### ISSUE THREAD

**Issue by floschne** [uhh-lt/dats#207]

**Comment by floschne** [comment]
Since we have decided on the new name, Digital Analysis Tool Suite (DATS), we have to reflect that (at least) in the UI, Docs, URL. That is: Wherever we wrote DWTS or D-WISE Tool Suite, we have to replace it with the new name. Maybe even rename the repo.

- [ ] replace DWTS with DATS in the UI
- [ ] replace DWTS with DATS in the GH Docs
- [ ] replace DWTS with DATS in the demo URL
- [ ] (maybe) replace DWTS with DATS in the backend (but idk if we really have to do this)

**Comment by bigabig** [comment]
i did this in #392
