### ISSUE TITLE
Memo Filtering is not working correctly

### ISSUE THREAD

**Issue by bigabig** [uhh-lt/dats#277]
This bug affects all Features that make use of the filtering system and allow to filter by memos.

In the Frontend, the memo of the currently logged-in user attached to the corresponding object is shown. 
However, multiple users can attach memos to any object.

In the following scenario, we will encounter bugs:
An object, e.g. annotation 1, has a memo "Hi" by user B.
User A filters by memo content contains "hi". This filter query will correctly return annotation 1, but in the frontend, no memo content is shown!

To Fix this, we need a memo renderer, that shows memos of all users of interest.

**Comment by mud1tx** [comment]
@bigabig I can work on this issue but can you please explain little more.

**Comment by bigabig** [comment]
i fixed this in #149 by restricting memo filters to the memos created by the logged in user.
