### ISSUE TITLE
A pre processing job is displayed as finished as soon as the first task is done

### ISSUE THREAD

**Issue by bigabig** [uhh-lt/dats#303]
To reproduce, upload multiple documents. Check the Background Jobs in Project Settings. As soon as the first job is finished, the whole preprocessing job is marked as finished.

**Comment by bigabig** [comment]
actually, the preprocessing job changes from running to finished during the upload.

**Comment by floschne** [comment]
Hmm, Ahmad and I tried to reproduce this but couldn't. We uploaded multiple docs and looked at the (visual) status indicator in the frontend. It seemed to work well
