### ISSUE TITLE
Remove `user_id` members from create DTOs

### ISSUE THREAD

**Issue by raffomania** [uhh-lt/dats#322]
When creating new entities, we usually record which user created them. Currently, the frontend passes a `user_id` field referencing the currently logged in user.

Since we now have the authorization user, we can remove the `user_id` field from the create DTOs and simply read the user id from the `AuthzUser` class instead.

**Comment by bigabig** [comment]
i removed all user_ids here: https://github.com/uhh-lt/dats/pull/429
