### ISSUE TITLE
ray container cannot be build in github CI: Not enough space

### ISSUE THREAD

**Issue by bigabig** [uhh-lt/dats#354]
It seems there is not enough space in the machines provided by Git Hub to build the ray container.

See: https://github.com/uhh-lt/dwts/actions/runs/7860742192/job/21448261739#logs

#9 21.13 OSError: [Errno 28] No space left on device

Can we reduce the build size?

**Comment by floschne** [comment]
Yes, we could try this: https://github.com/marketplace/actions/free-disk-space-ubuntu

**Comment by bigabig** [comment]
i did this in [766767b190f28fe974756d433278770b8bb3002d](https://github.com/uhh-lt/dats/commit/766767b190f28fe974756d433278770b8bb3002d)
