### ISSUE TITLE
User ID of span annotation

### ISSUE THREAD

**Issue by Alienmaster** [uhh-lt/dats#362]
When creating an annotation span in an annotation document, the user ID of the annotation document is returned instead of the user ID of the creator of the annotation span. This can occur if user1 has created the annotation document and user2 adds an annotation span.

The data structure of the span annotations must be extended for this.

**Comment by floschne** [comment]
This is a bug! It should not be possible for a user to write in an adoc of another user. There is always at max one adoc per user per sdoc.

**Comment by bigabig** [comment]
bitte lösen mit Validate im Endpoint. z.B. validate.validate_own_object(user_id, adoc_id)

**Comment by bigabig** [comment]
bitte auch für bbox annotations fixen
