### ISSUE TITLE
Removing an updated documentTag fails with a CircularDependencyError

### ISSUE THREAD

**Issue by Alienmaster** [uhh-lt/dats#368]
When removing an updated document Tag through the api it fails and returns the following error message: `sqlalchemy.exc.CircularDependencyError: Circular dependency detected.`

This only occurs on updated document Tags.

**Comment by bigabig** [comment]
fixed in #428 . Actually, there was a bug in the tests, linking the tag to itself. I changed the crud_tag update method to catch this and raise an exception.
