### ISSUE TITLE
Any working docker-compose.yml file?

### ISSUE THREAD

**Issue by fishfree** [uhh-lt/dats#371]
When I run docker-compose up -d by following the README, it says:
```
(base) meme@ubuntugpu:~/dwts/docker$ docker-compose up -d
WARNING: The SYSTEM_USER_FIRST_NAME variable is not set. Defaulting to a blank string.
WARNING: The SYSTEM_USER_LAST_NAME variable is not set. Defaulting to a blank string.
WARNING: The SYSTEM_USER_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The SYSTEM_USER_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The API_PORT variable is not set. Defaulting to a blank string.
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.dwts-backend-api.ports contains an invalid type, it should be a number, or an object
```
Then I ugly changed the 2 lines as :
```
    ports:
      - "5500:5500"
      - "8888:8888"
```
Then I run again ( I also run `./setup-folders.sh` before), it says:
```
(base) meme@ubuntugpu:~/dwts/docker$ docker-compose up -d
WARNING: The SYSTEM_USER_FIRST_NAME variable is not set. Defaulting to a blank string.
WARNING: The SYSTEM_USER_LAST_NAME variable is not set. Defaulting to a blank string.
WARNING: The SYSTEM_USER_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The SYSTEM_USER_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: Found orphan containers (docker_flowise_1, docker_worker_1, docker_web_1, docker_nginx_1, docker_db_1, docker_api_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
ERROR: Service "ray" was pulled in as a dependency of service "celery-background-jobs-worker" but is not enabled by the active profiles. You may fix this by adding a common profile to "ray" and "celery-background-jobs-worker".

```

**Comment by frawee** [comment]
I have a slightly different error, but the same problem:

`
$ docker compose up -d
WARN[0000] The "SYSTEM_USER_PASSWORD" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SYSTEM_USER_FIRST_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SYSTEM_USER_EMAIL" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SYSTEM_USER_LAST_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "API_PORT" variable is not set. Defaulting to a blank string. 
1 error(s) decoding:

* error decoding 'ports': No port specified: 5500:<empty>
`

**Comment by frawee** [comment]
I have a slightly different error, but the same problem:
```
$ docker compose up -d
WARN[0000] The "SYSTEM_USER_PASSWORD" variable is not set. Defaulting to a blank string.
WARN[0000] The "SYSTEM_USER_FIRST_NAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "SYSTEM_USER_EMAIL" variable is not set. Defaulting to a blank string.
WARN[0000] The "SYSTEM_USER_LAST_NAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "API_PORT" variable is not set. Defaulting to a blank string.
1 error(s) decoding:

error decoding 'ports': No port specified: 5500:
```

**Comment by bigabig** [comment]
I am very sorry for the late response. I updated the README.md with the correct instructions:

- host it on your own machine with `docker compose`
  - clone this repository: `git clone https://github.com/uhh-lt/dats.git`
  - navigate to the docker directory: `cd dats/docker`
  - create a copy of the .env.example file: `cp .env.example .env`
  - edit the .env example file and put in correct values for `UID`, `GID`, and `JWT_SECRET`
  - run `docker compose up -d`
  - visit [http://localhost:3000/](http://localhost:3000/) in your browser

Also, you can check our Wiki > Developer Guide for more advanced setups
