### ISSUE TITLE
Moving Finetune process from Celery to Ray

### ISSUE THREAD

**Issue by AhmadHAW** [uhh-lt/dats#385]
@floschne @bigabig hier mein technischer Lösungsansatz

So far refinement in the COTA pipeline happens in the Celery Worker. Because Celery is not well suited for ML-Tasks we want to move this pipeline step _finetune_st_ to a ray worker.
To do that I did the following things:

1. Analyze the current code flow from the API: _refine_cota_by_id_ to the pipeline step:  _finetune_st_.
2. Analyze how the ray worker is called and processed by example of _run_object_detection_.
3. Transform the _finetune_st_ step in a similar form how the other ray services are build.

I came up with the following tasks to make this happen:

1. Define a ray api endpoint for the _finetune_st_ step in _ray_model_service.py_. (Reuse _COTARefinementJobCreate_ and _COTARefinementJobRead_ as input and output types.
2. Create a cod_refinement.py in ray_model_worker/models and paste the the _finetune_st_ in there. 
3. Add a _cota_refinement_ function in _ray_model_service.py_, which doe the actual API call to the ray worker and have it return the validated _COTARefinementJobRead_.
4. Replace the content of _finetune_st_ pipeline with the newly added  _cota_refinement_ function of the _ray_model_service_.

Questions:

- The ray endpoints are awaiting for the result to be produced so far. What if the training takes longer, than an HTTP request can stay open?
- Do we want to use the init of the ray_model_worker model for COTA? This can preload models.

**Comment by bigabig** [comment]
done with #398
