### ISSUE TITLE
Starting COTA refinement with only one concept is not prohibited

### ISSUE THREAD

**Issue by AhmadHAW** [uhh-lt/dats#386]
As seen in the title. If a user tries to run the cota refinement process with only one concept, the pipeline fails in the finetune_st and throws an index out of bounds. For the refinement at least two concepts are needed. The user should be aware of this and stopped from starting a refinement job with only one concept.

**Comment by bigabig** [comment]
fixed here https://github.com/uhh-lt/dats/commit/f7615d057e2cc4e0883c68c547eb83b545003215
