### ISSUE TITLE
Ray Docker Build Kubernetes Legacy Package Repositories Frozen

### ISSUE THREAD

**Issue by AhmadHAW** [uhh-lt/dats#387]
Update (March 26, 2024): the legacy Google-hosted repositories went away on March 4, 2024. It's not possible to install Kubernetes packages from the legacy Google-hosted package repositories any longer. [see](https://kubernetes.io/blog/2023/08/31/legacy-package-repository-deprecation/)

This makes rebuilding the image of ray impossible, because _RUN sudo apt-get update_ runs into _The repository 'http://apt.kubernetes.io kubernetes-xenial Release' does not have a Release file._, which throws an exception.

**Comment by AhmadHAW** [comment]
@floschne @bigabig 
Changing to rayproject/ray-ml:latest-py310-gpu bas image fixes the problem, but results into
nvidia-container-cli: requirement error: unsatisfied condition: cuda>=11.8, please update your driver to a newer version, or use an earlier cuda container: unknown on runtime

(would happen with the rayproject/ray:latest-py310-gpu as well)
 
Current cuda driver is: 11.7.0

**Comment by bigabig** [comment]
we use `rayproject/ray:latest-py311-cu117` now and it works
