### ISSUE TITLE
double check cota file / repo paths

### ISSUE THREAD

**Issue by bigabig** [uhh-lt/dats#399]
ich bin mir nicht so sicher ob das mit den Dateipfaden aktuell so gut gelöst ist...

SHARED_REPO_ROOT. brauchen wir das wirklich?

Wie handeln wir model abspeichern und löschen? aktuell gibt es im repo service die funktion get_model_dir. im cota service wird das genutzt um bei einem reset das modell zu löschen.
Der ray model service hingegen hat seine eigene get_model_dir funktion... ob das so gut ist?

Ggf. muss hier refactored werden.

**Comment by AhmadHAW** [comment]
Der Grund warum ich diese Umgebungsvariable eingeführt habe ist, dass die Client Service Beziehung etwas seltsam war. Der Client hat bei Anfragen den absoluten pfad zur File im repo an den Service gesendet. Der Service soll dadurch den Pfad zur benötigten Datei finden.
Es kommt bei der Kombination vom lokalen Backend und Services im Docker zu Problemen, weil der absolute Pfad zur repo ein anderer ist.
Ich finde Clients sollten maximal einen relativen Pfad senden, besser sogar, nur Projekt ID und cota ID in diesem Fall und der Service setzt den absoluten Pfad zusammen, weil er selber weiß, wo sein repo root liegt. Diese Problem wird und bei der vertikalen Skalierung eh Probleme bereiten und wie müssen einen Service bereitstellen.
Ich habe also diese variable eingeführt, um allen Services die Information zu geben, wo ihre backed repo liegt. Diese können sich dann die Pfade selber zusammenbasteln.

**Comment by bigabig** [comment]
ok dann bleibt das wohl so :D
