### ISSUE TITLE
Where to see the analysis result or even of visualization result?

### ISSUE THREAD

**Issue by fishfree** [uhh-lt/dats#434]
I cannot see any analysis on discourses in [the demo CNN project](https://dats.ltdemos.informatik.uni-hamburg.de/project/2/search).

**Comment by bigabig** [comment]
Hi fishfree,

I think nobody has carried out a discourse analysis on these demo projects. 

The projects just show the results of our automatic pre-processing which includes steps like named entity recognition, language detection, keyword extraction, object detection etc.

This automatic pre-processing is performed by the SYSTEM USER. Consequently, if you want to see the extracted named entities of a document, in the annotator view, you have to select the SYSTEM USER to see her annotations.

![image](https://github.com/user-attachments/assets/4adfaed5-1816-43d7-8bcf-43cd9b1b45e8)

You could also try the Code Frequency analysis (Analysis > Code Frequency Analysis). Select SYSTEM USER and e.g. text as a modality. Next, click on the big System Code Bar to navigate the Code hierarchy and see more detailed analysis

**Comment by fishfree** [comment]
@bigabig Thank you!
