### ISSUE TITLE
sentencesearch returns images

### ISSUE THREAD

**Issue by bigabig** [uhh-lt/dats#442]
This similarity search should only return sentences / text files, right?

**Comment by bigabig** [comment]
![image](https://github.com/user-attachments/assets/bc4062f9-0009-464f-8577-0a24db27d148)

**Comment by bigabig** [comment]
i created a new project and just crawled this website: https://www.tagesschau.de/inland/innenpolitik/spd-miersch-generalsekretaer-100.html

**Comment by floschne** [comment]
It looks very suspicious to me... The similarity score between ANY image and ANY text is never higher than any text to another text. (commonly known as modality gap).

Might it be that this is a displaying bug or that some sdoc IDs got mixed up? Have you checked the raw output in the SwaggerUI ?
